### ISSUE TITLE
Story - Write Summaries of Tours

### ISSUE THREAD

**Issue by cmexcel** [rebelstackio/yakchat#170]
- [ ] Write summary for Intimar #175
- [ ]  Write summary for Barranco #174 
- [ ] Write summary for Machu Pichu #173 
- [ ] Write summary for Arequipa #172 
- [ ] Write summary for Islas Ballestas #171

Notes:
- Must identify max character length
- would be helpful to have an example summary 
- Must identify each type of summary, (will likely be different types of summaries for each tour in different sections of the site)
