### ISSUE TITLE
Story - Write itineraries for each tour

### ISSUE THREAD

**Issue by cmexcel** [rebelstackio/yakchat#181]
- [ ] Write Itinerary for Intimar #179 
- [ ]  Write Itinerary for Barranco #178  
- [ ] Write Itinerary for Machu Pichu #177  
- [ ] Write Itinerary for Arequipa #176  
- [ ] Write Itinerary for Islas Ballestas #180
